#!/bin/sh
cp ~/programming/dunyazad/experiments/single-choice-experiment/prospective-*-results-table.tex tab/
cp ~/programming/dunyazad/experiments/outcomes-experiment/reports/retrospective-*-table.tex tab/
cp ~/programming/dunyazad/experiments/outcomes-experiment/reports/legend.pdf fig/outcomes-legend.pdf
cp ~/programming/dunyazad/experiments/outcomes-experiment/reports/cropped-outcomes-report-*.pdf fig/
cp ~/programming/dunyazad/experiments/outcomes-experiment/reports/cropped-choices-*.pdf fig/
